export const BRANCHES = [
  "CSE",
  "ISE",
  "AI&ML",
  "AI&DS",
  "CSBS",
  "CS-IoT",
  "ECE",
  "EEE",
  "ETE",
  "EIE",
  "Civil",
  "ME",
  "Aerospace",
  "Chemical",
  "Biotechnology",
  "IEM",
  "Medical Electronics",
  "MCA",
  "MBA",
  "Other",
] as const;

export const BRANCH_CODES: Record<string, (typeof BRANCHES)[number]> = {
  cs: "CSE",
  is: "ISE",
  ai: "AI&ML",
  ad: "AI&DS",
  cb: "CSBS",
  it: "CS-IoT",
  ec: "ECE",
  ee: "EEE",
  et: "ETE",
  ei: "EIE",
  cv: "Civil",
  me: "ME",
  ae: "Aerospace",
  ch: "Chemical",
  bt: "Biotechnology",
  im: "IEM",
  ml: "Medical Electronics",
  ca: "MCA",
  ba: "MBA",
};
